In [2]:
import numpy as np 
a = [[1,2,3,],[4,5,6]]
b = np.array(a)
print(b)


[[1 2 3]
 [4 5 6]]


In [6]:
print('배열의 열수(차원):',b.ndim)
print('배열의 차원:',b.shape)
print(b[0,0]) #배열의 원소 접근
print(b[0,1])

배열의 열수(차원): 2
배열의 차원: (2, 3)
1
2


In [9]:
#영행렬 생성
print(np.zeros((2,2)))

#유닛행렬
print(np.ones((2,3)))

#모든 원소가 5인 2*3행렬
print(np.full((2,3),5))

#단위 행렬
print(np.eye(3))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#파이썬 numpy배열의 차원 변화
a = np.arange(20)
print('a:',a)

b = a.reshape(4,5)
print('b:',b)

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
b: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
#파이썬 numpy배열의 슬라이싱 및 인덱싱
lst = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lst)
a = arr[0:2, 0:2]
print(a)

b = arr[1:,1:]
print(b)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [23]:
#파이썬 numpy배열의 연산
a = np.array([1,2,3])
b = np.array([4,5,6])

#각 요소 더하기
#c = a + b

c = np.add(a,b)
print(c)

#각 요소 곱하기
#d = a * b
d = np.multiply(a,b)
print(d)

#각 요소 나누기
#e = a/b

e = np.divide(a,b)
print(e)




[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [24]:
#파이선 numpy 배열의 연산 - dot()
arr1 = [[1,2],[3,4]]
arr2 = [[5,6],[7,8]]
a = np.array(arr1)
b = np.array(arr2)

c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [31]:
#파이썬 numpy배열의 연산 - 모든 원소의 합: sum(), 모든 원소의 곱:pord()
a = np.array([[-1,2,3],[3,4,8]])
s = np.sum(a)
print('sum=',a.sum())

#행렬/열별 연산 (axis = 0/1)
print('sum by row=', a.sum(axis=0))

print('mean=',a.mean())

print('sd=',a.std())

print('product=',a.prod())

sum= 19
sum by row= [ 2  6 11]
mean= 3.1666666666666665
sd= 2.6718699236469
product= -576
